import { ReactNode } from 'react';

import "../styles/globals.css";
import Sidebar from './sidebar';

export default function RootLayout({children}: {children: ReactNode}) {
    return (
        <html lang="en">
            <head>
                <title>Sample Social</title>
                <meta name='description' content='Generated by create next app' />
            </head>
            <body className="flex h-screen">
                {/* Navigation */}
                <Sidebar />

                {/* Content */}
                <main className="flex-1 bg-zinc-300">
                    {children}
                </main>
            </body>
        </html>
    )
}